/**
 * PHARMACON PRESCRIPTION EXTRACTION ENGINE
 *
 * NOTE FOR DEVELOPERS / EVALUATORS:
 * -------------------------------------------------------------
 * STATUS: DEMO / ML MODEL PLANNED
 *
 * The actual deep-learning handwriting model (CNN-Transformer with
 * doctor-specific adapter weights) is currently in planning/training.
 *
 * This module isolates the extraction interface. When the real ML model
 * is deployed (e.g. via FastAPI or Supabase Edge Functions), replace
 * the implementation of `extractPrescription` with the real API call.
 * -------------------------------------------------------------
 */

export const EXTRACTION_ENGINE_STATUS = {
  isDemo: true,
  modelName: 'Pharmacon-Demo-Extractor-v0.2',
  targetArchitecture: 'TrOCR / CNN-Transformer with Low-Rank Doctor Adaptation (LoRA)',
  label: 'DEMO EXTRACTION (ML MODEL: PLANNED)',
};

/**
 * Extracts structured clinical fields from a prescription image.
 *
 * @param {string|File} _imageSource - Image URL or File object
 * @returns {Promise<{
 *   fields: Array<{ label: string, value: string, confidence: number, needsVerification: boolean }>,
 *   metadata: { extractedAt: string, engine: string, isDemo: boolean }
 * }>}
 */
export async function extractPrescription(_imageSource) {
  // Simulate network/inference latency
  await new Promise((resolve) => setTimeout(resolve, 800));

  const fields = [
    {
      label: 'Medicine',
      value: 'Amoxicillin',
      confidence: 94,
      needsVerification: false,
    },
    {
      label: 'Strength',
      value: '500 mg',
      confidence: 97,
      needsVerification: false,
    },
    {
      label: 'Dosage Form',
      value: 'Tablet',
      confidence: 96,
      needsVerification: false,
    },
    {
      label: 'Frequency',
      value: '1-0-1',
      confidence: 78,
      needsVerification: true,
    },
    {
      label: 'Route',
      value: 'Oral',
      confidence: 92,
      needsVerification: false,
    },
    {
      label: 'Duration',
      value: '5 days',
      confidence: 91,
      needsVerification: false,
    },
    {
      label: 'Instructions',
      value: 'After food',
      confidence: 84,
      needsVerification: true,
    },
  ];

  return {
    fields,
    metadata: {
      extractedAt: new Date().toISOString(),
      engine: EXTRACTION_ENGINE_STATUS.modelName,
      isDemo: true,
      note: 'Field values generated by demo extraction harness. Real doctor-adaptive model integration planned.',
    },
  };
}
