services:
  - type: web
    name: pharmacon-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
