-- ==============================================================================
-- PHARMACON SUPABASE DATABASE SCHEMA
-- Clean, robust PostgreSQL schema with Row Level Security (RLS) & Storage Buckets
-- ==============================================================================

-- Enable UUID extension
create extension if not exists "pgcrypto";

-- ------------------------------------------------------------------------------
-- 1. PROFILES (Linked to Supabase auth.users)
-- ------------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text not null,
  role text not null check (role in ('admin', 'doctor', 'clinic-staff', 'pharmacist', 'patient', 'instructor')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Helper functions for RLS
create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_role() in ('admin', 'instructor'), false);
$$;

-- ------------------------------------------------------------------------------
-- 2. TEAM MEMBERS (4-Person Team, Editable via Admin & App)
-- ------------------------------------------------------------------------------
create table if not exists public.team_members (
  id text primary key,
  name text not null,
  role text not null,
  focus text not null,
  skills text not null default '',
  avatar_url text default '',
  github_url text default '',
  linkedin_url text default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- ------------------------------------------------------------------------------
-- 3. INVENTORY ITEMS (Medicines & Stock)
-- ------------------------------------------------------------------------------
create table if not exists public.inventory_items (
  id text primary key,
  medicine text not null,
  generic_name text default '',
  strength text not null,
  dosage_form text not null,
  pack_size text not null,
  sku text unique not null,
  stock integer not null default 0 check (stock >= 0),
  reorder_level integer not null default 10,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- ------------------------------------------------------------------------------
-- 4. PRESCRIPTIONS (Uploaded Prescriptions)
-- ------------------------------------------------------------------------------
create table if not exists public.prescriptions (
  id text primary key,
  patient_id text not null,
  patient_name text not null,
  doctor_name text not null,
  image_url text default '',
  status text not null check (status in ('draft', 'confirmed', 'dispensed')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- ------------------------------------------------------------------------------
-- 5. PRESCRIPTION FIELDS (Extracted Structured Data)
-- ------------------------------------------------------------------------------
create table if not exists public.prescription_fields (
  id bigint generated by default as identity primary key,
  prescription_id text not null references public.prescriptions(id) on delete cascade,
  label text not null,
  value text not null,
  confidence integer not null check (confidence >= 0 and confidence <= 100),
  needs_verification boolean not null default false
);

-- ------------------------------------------------------------------------------
-- 6. REFILL REQUESTS (Patient Requests & Pharmacy Approvals)
-- ------------------------------------------------------------------------------
create table if not exists public.refill_requests (
  id text primary key,
  prescription_id text references public.prescriptions(id) on delete set null,
  patient_id text not null,
  patient_name text not null default '',
  medicine text not null,
  strength text not null,
  status text not null check (status in ('pending', 'approved', 'rejected', 'contacted')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- ------------------------------------------------------------------------------
-- 7. AUDIT EVENTS (System Activity Log)
-- ------------------------------------------------------------------------------
create table if not exists public.audit_events (
  id text primary key,
  actor_id text default '',
  actor_name text not null,
  actor_role text not null,
  action text not null,
  entity text not null,
  entity_id text not null,
  details text default '',
  created_at timestamptz not null default timezone('utc', now())
);

-- ------------------------------------------------------------------------------
-- 8. VERSIONS (Release History & Deliverable Milestones)
-- ------------------------------------------------------------------------------
create table if not exists public.versions (
  id text primary key,
  name text not null,
  date text not null,
  authors text not null,
  status text not null check (status in ('current', 'archived', 'future', 'draft')),
  change_summary text not null default '',
  deployment_url text default '',
  file_url text default '',
  created_at timestamptz not null default timezone('utc', now())
);

-- ------------------------------------------------------------------------------
-- 9. DELIVERABLES (Platform Artifacts, Documents, Reports)
-- ------------------------------------------------------------------------------
create table if not exists public.deliverables (
  id text primary key,
  title text not null,
  type text not null,
  version_id text references public.versions(id) on delete set null,
  date text not null,
  status text not null check (status in ('draft', 'in-progress', 'published', 'archived')),
  description text not null default '',
  file_path text default '',
  file_name text default '',
  file_url text default '',
  created_at timestamptz not null default timezone('utc', now())
);

-- ------------------------------------------------------------------------------
-- 10. PRESENTATION DECKS (PowerPoint Pitch Decks)
-- ------------------------------------------------------------------------------
create table if not exists public.presentation_decks (
  id text primary key,
  title text not null,
  description text not null default '',
  file_path text not null default '',
  file_url text default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

-- ------------------------------------------------------------------------------
-- STORAGE BUCKETS
-- ------------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values
  ('team-assets', 'team-assets', true, 10485760),
  ('prescriptions', 'prescriptions', true, 20971520),
  ('presentations', 'presentations', true, 104857600),
  ('deliverables', 'deliverables', true, 104857600)
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit;

-- ------------------------------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ------------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.team_members enable row level security;
alter table public.inventory_items enable row level security;
alter table public.prescriptions enable row level security;
alter table public.prescription_fields enable row level security;
alter table public.refill_requests enable row level security;
alter table public.audit_events enable row level security;
alter table public.versions enable row level security;
alter table public.deliverables enable row level security;
alter table public.presentation_decks enable row level security;

-- Profiles Policies
drop policy if exists "Profiles are readable by authenticated users" on public.profiles;
create policy "Profiles are readable by authenticated users"
  on public.profiles for select to authenticated using (true);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "Admins can manage all profiles" on public.profiles;
create policy "Admins can manage all profiles"
  on public.profiles for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Team Members Policies (Public read, admin/authenticated manage)
drop policy if exists "Team members public read" on public.team_members;
create policy "Team members public read" on public.team_members for select using (true);

drop policy if exists "Authenticated users can update team members" on public.team_members;
create policy "Authenticated users can update team members" on public.team_members for all to authenticated using (true) with check (true);

-- Inventory Items Policies (Public/authenticated read, staff/admin manage)
drop policy if exists "Inventory items read" on public.inventory_items;
create policy "Inventory items read" on public.inventory_items for select using (true);

drop policy if exists "Inventory items manage" on public.inventory_items;
create policy "Inventory items manage" on public.inventory_items for all to authenticated using (true) with check (true);

-- Prescriptions Policies
drop policy if exists "Prescriptions read" on public.prescriptions;
create policy "Prescriptions read" on public.prescriptions for select using (true);

drop policy if exists "Prescriptions manage" on public.prescriptions;
create policy "Prescriptions manage" on public.prescriptions for all to authenticated using (true) with check (true);

-- Prescription Fields Policies
drop policy if exists "Prescription fields read" on public.prescription_fields;
create policy "Prescription fields read" on public.prescription_fields for select using (true);

drop policy if exists "Prescription fields manage" on public.prescription_fields;
create policy "Prescription fields manage" on public.prescription_fields for all to authenticated using (true) with check (true);

-- Refill Requests Policies
drop policy if exists "Refills read" on public.refill_requests;
create policy "Refills read" on public.refill_requests for select using (true);

drop policy if exists "Refills manage" on public.refill_requests;
create policy "Refills manage" on public.refill_requests for all to authenticated using (true) with check (true);

-- Audit Events Policies
drop policy if exists "Audit events read" on public.audit_events;
create policy "Audit events read" on public.audit_events for select using (true);

drop policy if exists "Audit events insert" on public.audit_events;
create policy "Audit events insert" on public.audit_events for insert with check (true);

-- Versions Policies
drop policy if exists "Versions read" on public.versions;
create policy "Versions read" on public.versions for select using (true);

drop policy if exists "Versions manage" on public.versions;
create policy "Versions manage" on public.versions for all to authenticated using (true) with check (true);

-- Deliverables Policies
drop policy if exists "Deliverables read" on public.deliverables;
create policy "Deliverables read" on public.deliverables for select using (true);

drop policy if exists "Deliverables manage" on public.deliverables;
create policy "Deliverables manage" on public.deliverables for all to authenticated using (true) with check (true);

-- Presentation Decks Policies
drop policy if exists "Presentation decks read" on public.presentation_decks;
create policy "Presentation decks read" on public.presentation_decks for select using (true);

drop policy if exists "Presentation decks manage" on public.presentation_decks;
create policy "Presentation decks manage" on public.presentation_decks for all to authenticated using (true) with check (true);

-- Storage Objects Policies
drop policy if exists "Public storage read" on storage.objects;
create policy "Public storage read" on storage.objects for select using (true);

drop policy if exists "Authenticated storage insert" on storage.objects;
create policy "Authenticated storage insert" on storage.objects for insert to authenticated with check (true);

drop policy if exists "Authenticated storage update" on storage.objects;
create policy "Authenticated storage update" on storage.objects for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated storage delete" on storage.objects;
create policy "Authenticated storage delete" on storage.objects for delete to authenticated using (true);

-- ------------------------------------------------------------------------------
-- TRANSACTIONAL RPC FOR CONFIRMATION & SAFE INVENTORY UPDATE
-- ------------------------------------------------------------------------------
create or replace function public.confirm_prescription_and_update_stock(
  p_prescription_id text,
  p_medicine_name text,
  p_actor_name text,
  p_actor_role text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item record;
  v_deducted boolean := false;
begin
  -- 1. Update prescription status
  update public.prescriptions
  set status = 'confirmed', updated_at = timezone('utc', now())
  where id = p_prescription_id;

  -- 2. Try to match medicine in inventory and safely deduct 1 pack
  select * into v_item
  from public.inventory_items
  where lower(medicine) = lower(p_medicine_name)
  limit 1;

  if found and v_item.stock > 0 then
    update public.inventory_items
    set stock = stock - 1, updated_at = timezone('utc', now())
    where id = v_item.id;
    v_deducted := true;
  end if;

  -- 3. Log audit event
  insert into public.audit_events (id, actor_name, actor_role, action, entity, entity_id, details)
  values (
    'AE-' || substr(gen_random_uuid()::text, 1, 8),
    p_actor_name,
    p_actor_role,
    'Prescription confirmed' || (case when v_deducted then ' & inventory stock deducted' else '' end),
    'Prescription',
    p_prescription_id,
    'Confirmed prescription ' || p_prescription_id || ' for ' || p_medicine_name
  );

  return jsonb_build_object(
    'success', true,
    'prescription_id', p_prescription_id,
    'stock_deducted', v_deducted
  );
end;
$$;

-- ------------------------------------------------------------------------------
-- SEED INITIAL DATA
-- ------------------------------------------------------------------------------
insert into public.team_members (id, name, role, focus, skills, avatar_url, github_url, linkedin_url)
values
  ('T-001', 'Aryan Sharma', 'Frontend Lead', 'UI/UX architecture, responsive design system, tactile component library, and interactive presentations.', 'React, JavaScript, Tailwind CSS, Lucide Icons', '', 'https://github.com', 'https://linkedin.com'),
  ('T-002', 'Aniket Raj', 'Backend Lead', 'Supabase architecture, PostgreSQL persistence, storage integrations, and release publishing engine.', 'JavaScript, PostgreSQL, Supabase, Storage, RLS', '', 'https://github.com', 'https://linkedin.com'),
  ('T-003', 'Amitesh Kumar Singh', 'AI / CV Engineer', 'Handwriting segmentation pipeline, CNN-Transformer feature models, and doctor-adaptive calibration loops.', 'Python, PyTorch, Computer Vision, OCR, ML', '', 'https://github.com', 'https://linkedin.com'),
  ('T-004', 'Chirag Lamba', 'Integration Lead', 'Formulary SKU matching algorithms, security audit controls, end-to-end reliability verification, and CI/CD pipelines.', 'CI/CD, GitHub Actions, System Integration, Testing', '', 'https://github.com', 'https://linkedin.com')
on conflict (id) do update set
  name = excluded.name,
  role = excluded.role,
  focus = excluded.focus,
  skills = excluded.skills,
  github_url = excluded.github_url,
  linkedin_url = excluded.linkedin_url;

insert into public.inventory_items (id, medicine, generic_name, strength, dosage_form, pack_size, sku, stock, reorder_level)
values
  ('INV-001', 'Amoxicillin', 'Amoxicillin Trihydrate', '500 mg', 'Capsule', '100 caps', 'AMX-500-CAP', 142, 25),
  ('INV-002', 'Metformin', 'Metformin Hydrochloride', '500 mg', 'Tablet', '60 tabs', 'MET-500-TAB', 18, 20),
  ('INV-003', 'Paracetamol', 'Acetaminophen', '650 mg', 'Tablet', '100 tabs', 'PAR-650-TAB', 240, 30),
  ('INV-004', 'Azithromycin', 'Azithromycin Dihydrate', '500 mg', 'Tablet', '30 tabs', 'AZI-500-TAB', 8, 15),
  ('INV-005', 'Omeprazole', 'Omeprazole Magnesium', '20 mg', 'Capsule', '100 caps', 'OMP-020-CAP', 89, 25),
  ('INV-006', 'Cetirizine', 'Cetirizine Hydrochloride', '10 mg', 'Tablet', '100 tabs', 'CTZ-010-TAB', 200, 40),
  ('INV-007', 'Atorvastatin', 'Atorvastatin Calcium', '10 mg', 'Tablet', '100 tabs', 'ATV-010-TAB', 45, 20),
  ('INV-008', 'Ibuprofen', 'Ibuprofen', '400 mg', 'Tablet', '100 tabs', 'IBP-400-TAB', 12, 25)
on conflict (id) do update set
  medicine = excluded.medicine,
  generic_name = excluded.generic_name,
  strength = excluded.strength,
  dosage_form = excluded.dosage_form,
  pack_size = excluded.pack_size,
  stock = excluded.stock,
  reorder_level = excluded.reorder_level;

insert into public.prescriptions (id, patient_id, patient_name, doctor_name, image_url, status)
values
  ('RX-2024-0001', 'PT-1001', 'Rahul Kumar', 'Dr. A. Sharma', '', 'confirmed'),
  ('RX-2024-0002', 'PT-1002', 'Meera Patel', 'Dr. R. Gupta', '', 'draft')
on conflict (id) do nothing;

insert into public.prescription_fields (prescription_id, label, value, confidence, needs_verification)
values
  ('RX-2024-0001', 'Medicine', 'Amoxicillin', 94, false),
  ('RX-2024-0001', 'Strength', '500 mg', 97, false),
  ('RX-2024-0001', 'Dosage Form', 'Tablet', 96, false),
  ('RX-2024-0001', 'Frequency', '1-0-1', 86, true),
  ('RX-2024-0001', 'Route', 'Oral', 92, false),
  ('RX-2024-0001', 'Duration', '5 days', 91, false),
  ('RX-2024-0001', 'Instructions', 'After food', 88, true),
  ('RX-2024-0002', 'Medicine', 'Metformin', 92, false),
  ('RX-2024-0002', 'Strength', '500 mg', 89, false),
  ('RX-2024-0002', 'Dosage Form', 'Tablet', 95, false),
  ('RX-2024-0002', 'Frequency', '1-0-1', 74, true),
  ('RX-2024-0002', 'Route', 'Oral', 90, false),
  ('RX-2024-0002', 'Duration', '30 days', 93, false),
  ('RX-2024-0002', 'Instructions', 'With evening meal', 82, true)
on conflict do nothing;

insert into public.refill_requests (id, prescription_id, patient_id, patient_name, medicine, strength, status)
values
  ('RF-001', 'RX-2024-0001', 'PT-1001', 'Rahul Kumar', 'Amoxicillin', '500 mg', 'pending'),
  ('RF-002', 'RX-2024-0002', 'PT-1002', 'Meera Patel', 'Metformin', '500 mg', 'approved')
on conflict (id) do nothing;

insert into public.audit_events (id, actor_name, actor_role, action, entity, entity_id, details)
values
  ('AE-001', 'System Admin', 'admin', 'Database initialized and seeded', 'System', 'INIT', 'Initial schema deployment and seeding'),
  ('AE-002', 'Dr. A. Sharma', 'doctor', 'Prescription uploaded', 'Prescription', 'RX-2024-0001', 'Initial sample prescription upload'),
  ('AE-003', 'Priya Desai', 'clinic-staff', 'Prescription verified and confirmed', 'Prescription', 'RX-2024-0001', 'Confirmed by clinic staff'),
  ('AE-004', 'Rahul Kumar', 'patient', 'Refill requested', 'RefillRequest', 'RF-001', 'Patient initiated refill request for Amoxicillin')
on conflict (id) do nothing;

insert into public.versions (id, name, date, authors, status, change_summary, deployment_url, file_url)
values
  ('v1.0.0', 'Planning Presentation v1', '2026-08-25', 'Aryan Sharma, Aniket Raj, Amitesh Kumar Singh, Chirag Lamba', 'current', 'Initial project planning deliverable covering scope, intended users, system architecture, performance goals, technical risks, and interactive Gantt roadmap.', '#/presentation/v1', '/presentations/Pharmacon_Commitment_Pitch.pptx'),
  ('v2.0.0', 'Planning Presentation v2', '2026-09-10', 'Team Pharmacon', 'future', 'Refined scope addressing writer recruitment milestones, real clinic calibration workflows, and Supabase integration.', '#/presentation/v2', '/presentations/Merged_Presentation_from_Claude.pptx')
on conflict (id) do update set
  name = excluded.name,
  date = excluded.date,
  authors = excluded.authors,
  status = excluded.status,
  change_summary = excluded.change_summary,
  deployment_url = excluded.deployment_url,
  file_url = excluded.file_url;

insert into public.deliverables (id, title, type, version_id, date, status, description, file_name, file_url)
values
  ('deliv-v1-deck', 'Planning Presentation v1 (Interactive Web Deck)', 'Interactive Presentation', 'v1.0.0', '2026-08-25', 'published', 'Direct browser-delivered planning presentation satisfying all clinical engineering requirements.', 'Pharmacon_Commitment_Pitch.pptx', '/presentations/Pharmacon_Commitment_Pitch.pptx'),
  ('deliv-v2-deck', 'Planning Presentation v2 (Scope & Feedback Updates)', 'Interactive Presentation', 'v2.0.0', '2026-09-10', 'published', 'Updated planning deliverable incorporating clinical advisory feedback and revised architecture.', 'Merged_Presentation_from_Claude.pptx', '/presentations/Merged_Presentation_from_Claude.pptx')
on conflict (id) do update set
  title = excluded.title,
  type = excluded.type,
  version_id = excluded.version_id,
  date = excluded.date,
  status = excluded.status,
  description = excluded.description,
  file_name = excluded.file_name,
  file_url = excluded.file_url;

insert into public.presentation_decks (id, title, description, file_path, file_url, sort_order)
values
  ('DECK-001', 'Pharmacon Commitment Pitch', 'Revised scope, doctor-adaptive recognition strategy, roadmap and approval requirements.', '/presentations/Pharmacon_Commitment_Pitch.pptx', '/presentations/Pharmacon_Commitment_Pitch.pptx', 0),
  ('DECK-002', 'Merged Project Ideas Presentation', 'Original team project-ideas deck, including the medication-scheduling concept that preceded Pharmacon''s revised scope.', '/presentations/Merged_Presentation_from_Claude.pptx', '/presentations/Merged_Presentation_from_Claude.pptx', 1)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  file_path = excluded.file_path,
  file_url = excluded.file_url,
  sort_order = excluded.sort_order;
